### ISSUE TITLE
CORS Settings in Discourse

### ISSUE THREAD

**Issue by bmann** [fission-suite/filecoin-backup#8]
To embed JSON of Discourse files in the community section in the app, CORS settings in Discourse need to be adjusted.

See (internal) Fission thread https://talk.fission.codes/t/cross-site-discourse-rss-feeds/1530

**Comment by bmann** [comment]
@walkah assigning to you to see if you can have more luck? I flipped settings on the server Docker instance and rebuilt, but not really sure what else to do.

Not high priority, just needs some full stack network tinkering at some point.

Would like to solve this generally to be able to embed things from our Discourse in various other places -- e.g. Drive.

**Comment by walkah** [comment]
Okay! I'll have a look at this today

**Comment by bgins** [comment]
Adding a note that the [feature/discourse-feed](/fission-suite/filecoin-backup/tree/feature/discourse-feed) branch has an implementation that should fetch and display links to posts tagged with `filecoin` on the forum. These are pulled from https://talk.fission.codes/tags/filecoin.json.

**Comment by walkah** [comment]
A month later, but this is working. @bgins just a note the feed is : `https://talk.fission.codes/tag/filecoin.json` ("tag" not "tags"). I pushed the URL fix to the branch.

**Comment by bgins** [comment]
Awesome, thanks for the help with this! :pray:
